### ISSUE TITLE
Increase max string length to 512

### ISSUE THREAD

**Issue by MacMcIrish** [blackflux/lambda-monitor-logger#43]
https://github.com/blackflux/lambda-monitor-logger/blob/b5c2dd22feb0871a6ec3c6559e6d54ca4e2debbf/src/logic/abbrev.js#L3

128 is still too restricting

**Comment by simlu** [comment]
Have to agree on a good limit... 512 and see where that gets us?

**Comment by guptashak90** [comment]
**you can take**  @MacMcIrish 
Max string length is:
1073741799 characters

**Comment by simlu** [comment]
@guptashak90 This in a function that is used to abbreviate object serialization. So you comment doesn't really make sense?
